spring:
  application:
    name: pdv-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pdv}
    username: ${DB_USERNAME:admin_pdv}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false # En prod déjalo en false para no saturar disco ni exponer datos en logs
    properties:
      hibernate:
        format-sql: false
server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:8400000}